extends Node

enum EInstruction{
	ADD,
	ADDri,
	ADDir,
	SUB,
	SUBri,
	SUBir,
	MUL,
	MULri,
	MULir,
	DIV,
	DIVri,
	DIVir,
	MOD,
	MODri,
	MODir,
	MIN,
	MINri,
	MINir,
	MAX,
	MAXri,
	MAXir,
	NEG,
	AND,
	ANDri,
	ANDir,
	ORR,
	ORRri,
	ORRir,
	NOT,
	NOTri,
	NOTir,
	XOR,
	XORri,
	XORir,
	JMP,
	JGT,
	JLT,
	JEQ,
	JNE,
	JGE,
	JLE,
	JAL,
	STR,
	LDR,
	MOV,
	END,
	LBL,
	NOP,}

enum ERegister{
	r00,
	r01,
	r02,
	r03,
	r04,
	r05,
	r08,
	r09,
	r0A,
	r0B,
	r0C,
	r0D,
	r0E,
	r0F,
	r10,}

var instruction_map: Dictionary = {
	"ADD"	: self.EInstruction.ADD,
	"ADDri"	: self.EInstruction.ADDri,
	"ADDir"	: self.EInstruction.ADDir,
	"SUB"	: self.EInstruction.SUB,
	"SUBri"	: self.EInstruction.SUBri,
	"SUBir"	: self.EInstruction.SUBir,
	"MUL"	: self.EInstruction.MUL,
	"MULri"	: self.EInstruction.MULri,
	"MULir"	: self.EInstruction.MULir,
	"DIV"	: self.EInstruction.DIV,
	"DIVri"	: self.EInstruction.DIVri,
	"DIVir"	: self.EInstruction.DIVir,
	"MOD"	: self.EInstruction.MOD,
	"MODri"	: self.EInstruction.MODri,
	"MODir"	: self.EInstruction.MODir,
	"MIN"	: self.EInstruction.MIN,
	"MINri"	: self.EInstruction.MINri,
	"MINir"	: self.EInstruction.MINir,
	"MAX"	: self.EInstruction.MAX,
	"MAXri"	: self.EInstruction.MAXri,
	"MAXir"	: self.EInstruction.MAXir,
	"NEG"	: self.EInstruction.NEG,
	"AND"	: self.EInstruction.AND,
	"ANDri"	: self.EInstruction.ANDri,
	"ANDir"	: self.EInstruction.ANDir,
	"ORR"	: self.EInstruction.ORR,
	"ORRri"	: self.EInstruction.ORRri,
	"ORRir"	: self.EInstruction.ORRir,
	"NOT"	: self.EInstruction.NOT,
	"NOTri"	: self.EInstruction.NOTri,
	"NOTir"	: self.EInstruction.NOTir,
	"XOR"	: self.EInstruction.XOR,
	"XORri"	: self.EInstruction.XORri,
	"XORir"	: self.EInstruction.XORir,
	"JMP"	: self.EInstruction.JMP,
	"JGT"	: self.EInstruction.JGT,
	"JLT"	: self.EInstruction.JLT,
	"JEQ"	: self.EInstruction.JEQ,
	"JNE"	: self.EInstruction.JNE,
	"JGE"	: self.EInstruction.JGE,
	"JLE"	: self.EInstruction.JLE,
	"JAL"	: self.EInstruction.JAL,
	"STR"	: self.EInstruction.STR,
	"LDR"	: self.EInstruction.LDR,
	"MOV"	: self.EInstruction.MOV,
	"END"	: self.EInstruction.END,
	"LBL"	: self.EInstruction.LBL,
	"NOP"	: self.EInstruction.NOP,}

var register_map: Dictionary = {
	"r00":self.ERegister.r00,
	"r01":self.ERegister.r01,
	"r02":self.ERegister.r02,
	"r03":self.ERegister.r03,
	"r04":self.ERegister.r04,
	"r05":self.ERegister.r05,
	"r08":self.ERegister.r08,
	"r09":self.ERegister.r09,
	"r0A":self.ERegister.r0A,
	"r0B":self.ERegister.r0B,
	"r0C":self.ERegister.r0C,
	"r0D":self.ERegister.r0D,
	"r0E":self.ERegister.r0E,
	"r0F":self.ERegister.r0F,
	"r10":self.ERegister.r10,}
