extends Node

enum EInstruction{
	ADD,
	ADDri,
	ADDir,
	SUB,
	SUBri,
	SUBir,
	MUL,
	MULri,
	MULir,
	DIV,
	DIVri,
	DIVir,
	MOD,
	MODri,
	MODir,
	MIN,
	MINri,
	MINir,
	MAX,
	MAXri,
	MAXir,
	NEG,
	AND,
	ANDri,
	ANDir,
	ORR,
	ORRri,
	ORRir,
	NOT,
	XOR,
	XORri,
	XORir,
	JMP,
	JGT,
	JLT,
	JEQ,
	JNE,
	JGE,
	JLE,
	JAL,
	STR,
	LDR,
	MOV,
	END,
	LBL,
	NOP,}

enum EOperandType{
	INSTRUCTION,
	REGISTER,
	IMMEDIATE,
	LABEL,
	COMMENT,
	UNKNOWN,}

enum ERegister{
	r0,
	r1,
	r2,
	r3,
	r4,
	r5,
	r8,
	r9,
	rA,
	rB,
	rC,
	rD,
	rE,
	rF,}

var instruction_map: Dictionary = {
	"ADD"	: self.EInstruction.ADD,
	"ADDri"	: self.EInstruction.ADDri,
	"ADDir"	: self.EInstruction.ADDir,
	"SUB"	: self.EInstruction.SUB,
	"SUBri"	: self.EInstruction.SUBri,
	"SUBir"	: self.EInstruction.SUBir,
	"MUL"	: self.EInstruction.MUL,
	"MULri"	: self.EInstruction.MULri,
	"MULir"	: self.EInstruction.MULir,
	"DIV"	: self.EInstruction.DIV,
	"DIVri"	: self.EInstruction.DIVri,
	"DIVir"	: self.EInstruction.DIVir,
	"MOD"	: self.EInstruction.MOD,
	"MODri"	: self.EInstruction.MODri,
	"MODir"	: self.EInstruction.MODir,
	"MIN"	: self.EInstruction.MIN,
	"MINri"	: self.EInstruction.MINri,
	"MINir"	: self.EInstruction.MINir,
	"MAX"	: self.EInstruction.MAX,
	"MAXri"	: self.EInstruction.MAXri,
	"MAXir"	: self.EInstruction.MAXir,
	"NEG"	: self.EInstruction.NEG,
	"AND"	: self.EInstruction.AND,
	"ANDri"	: self.EInstruction.ANDri,
	"ANDir"	: self.EInstruction.ANDir,
	"ORR"	: self.EInstruction.ORR,
	"ORRri"	: self.EInstruction.ORRri,
	"ORRir"	: self.EInstruction.ORRir,
	"NOT"	: self.EInstruction.NOT,
	"XOR"	: self.EInstruction.XOR,
	"XORri"	: self.EInstruction.XORri,
	"XORir"	: self.EInstruction.XORir,
	"JMP"	: self.EInstruction.JMP,
	"JGT"	: self.EInstruction.JGT,
	"JLT"	: self.EInstruction.JLT,
	"JEQ"	: self.EInstruction.JEQ,
	"JNE"	: self.EInstruction.JNE,
	"JGE"	: self.EInstruction.JGE,
	"JLE"	: self.EInstruction.JLE,
	"JAL"	: self.EInstruction.JAL,
	"STR"	: self.EInstruction.STR,
	"LDR"	: self.EInstruction.LDR,
	"MOV"	: self.EInstruction.MOV,
	"END"	: self.EInstruction.END,
	"LBL"	: self.EInstruction.LBL,
	"NOP"	: self.EInstruction.NOP,}

var register_map: Dictionary = {
	"r0":self.ERegister.r0,
	"r1":self.ERegister.r1,
	"r2":self.ERegister.r2,
	"r3":self.ERegister.r3,
	"r4":self.ERegister.r4,
	"r5":self.ERegister.r5,
	"r8":self.ERegister.r8,
	"r9":self.ERegister.r9,
	"rA":self.ERegister.rA,
	"rB":self.ERegister.rB,
	"rC":self.ERegister.rC,
	"rD":self.ERegister.rD,
	"rE":self.ERegister.rE,
	"rF":self.ERegister.rF,}
